/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "secondary-fixed": "#d4e3ff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#a5c8ff",
        error: "#ba1a1a",
        primary: "#0d631b",
        "inverse-primary": "#88d982",
        "surface-container-high": "#eae7e7",
        tertiary: "#923357",
        "primary-fixed-dim": "#88d982",
        "tertiary-fixed": "#ffd9e2",
        "on-tertiary-fixed": "#3f001c",
        "tertiary-fixed-dim": "#ffb1c7",
        "on-primary-container": "#cbffc2",
        "tertiary-container": "#b14b6f",
        "secondary-container": "#54a0fe",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "on-primary-fixed-variant": "#005312",
        "error-container": "#ffdad6",
        secondary: "#005faf",
        outline: "#707a6c",
        "inverse-on-surface": "#f3f0ef",
        "surface-container": "#f0eded",
        "surface-variant": "#e5e2e1",
        "primary-fixed": "#a3f69c",
        "on-secondary-container": "#003567",
        "on-secondary-fixed-variant": "#004786",
        "on-surface": "#1b1c1c",
        "on-error-container": "#93000a",
        "surface-tint": "#1b6d24",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#002204",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#001c3a",
        "on-background": "#1b1c1c",
        "inverse-surface": "#303030",
        surface: "#fcf9f8",
        "on-tertiary-container": "#ffedf0",
        "surface-container-highest": "#e5e2e1",
        "surface-container-low": "#f6f3f2",
        background: "#fcf9f8",
        "on-tertiary-fixed-variant": "#7f2448",
        "primary-container": "#2e7d32",
        "on-surface-variant": "#40493d",
        "on-error": "#ffffff",
        "outline-variant": "#bfcaba",
      },
      fontFamily: {
        display: ["Manrope", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
